### ISSUE TITLE
issue with installation

### ISSUE THREAD

**Issue by avivli** [hfoffani/pddl-lib#17]
![image](https://user-images.githubusercontent.com/35082204/34542724-7431d172-f0e6-11e7-9bdf-ce2dab9b943b.png)

can anyone knows what is the problem- download it and install through gitHub

**Comment by hfoffani** [comment]
Hi,
I'll test the installation in a new environment to see if I can reproduce it. I'll let you know what I find.

**Comment by hfoffani** [comment]
I have pushed an update that I think it may fix the problem.
To install locally just call `make pydist`. Remember that you need to install `antlr4-python3-runtime` previously.
I see that you are using Anaconda. Just make sure that the environment you use in your project is the same when building pddlpy. 
Check the results with `pip list` in your environment. You should see the `antlr` and the `pddlpy` packages.
Let me know if it works.
Thanks!

**Comment by avivli** [comment]
just to try to download the pddl library again ?

**Comment by avivli** [comment]
when trying to install it like this in anaconda3 : pip install git+https://github.com/hfoffani/pddl-lib.git
all the installation seems to looks fine but when trying to use the library is still not working. 
they both appear in the pip list.

**Comment by hfoffani** [comment]
Uh.. I'm sorry! I misunderstood you. I've never tried pip+git before. I don't think it would work though, because the library needs the grammar to be "compiled".

There are two alternatives:
1. Install from pypi: `pip install pddlpy`.
2. clone the repository, install the antlr4-python3-runtime if you don't have it, and run `make pydist` from the repo root directory. I haven't tested this option in a Windows environment so I don't know if it works.

**Comment by avivli** [comment]
Hi !
thank for your help, it work finally. but is seems not to read my files of the domain correctly- all the oerators are not initializes due the fact that I'm using strips probablisitic effect pddl format. is the parser doesn't support this format?
![image](https://user-images.githubusercontent.com/35082204/34603599-3944e64e-f20d-11e7-9e9d-a78239b9d34a.png)

aviv

**Comment by hfoffani** [comment]
Glad it worked.

I'm affraid but no, the grammar currently doesn't support probabilistic effects.
To be useful, besides probabilistic states, it would also require to implement conditional effects.
